services:
  app:
    build: .
    container_name: weather-app
    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

    depends_on:
      db:
        condition: service_healthy

      
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  
  db:
    image: postgres:17-alpine
    container_name: weather-db
    restart: unless-stopped
    

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


    volumes:
      - postgres_data:/var/lib/postgresql/data
    

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: